baseURL = "https://x7c0de0x.tech/"
languageCode = "en-us"
title = "x7c0de0x"
theme = "hello-friend-ng"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact Us"
    url = "/contact/"
    weight = 4

[params]
  defaultTheme = "dark"
  themeColor = "#fe8019"
  customCSS = ["/css/custom.css"]

  [params.Logo]
    logoMark = ">"
    logoText = "x7c0de0x"
    logoCursorColor = "#fe8019"
